[project]
name = "oceanography_with_flowers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cmocean>=4.0.3",
    "ipykernel>=7.3.0",
    "matplotlib>=3.10.9",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "xarray>=2025.6.1",
    "xcmocean>=0.3.2",
    "xroms>=0.6.2",
    "zarr>=2.18.3",
]

[project.scripts]
oceanography-with-flowers = "oceanography_with_flowers:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
